In [2]:
using Plots, LinearAlgebra, MatrixDepot, IterativeSolvers

# MTH8107 Mathématiques de l'apprentissage Profond : Devoir 2
## Bertrand Toutée 1805477 et Victor Gaudreau-Blouin 

### Question 1

#### a)

In [8]:
? diagm

search: diagm diag diagind Diagonal isdiag Bidiagonal Tridiagonal SymTridiagonal



```
diagm(kv::Pair{<:Integer,<:AbstractVector}...)
diagm(m::Integer, n::Integer, kv::Pair{<:Integer,<:AbstractVector}...)
```

Construct a matrix from `Pair`s of diagonals and vectors. Vector `kv.second` will be placed on the `kv.first` diagonal. By default the matrix is square and its size is inferred from `kv`, but a non-square size `m`×`n` (padded with zeros as needed) can be specified by passing `m,n` as the first arguments.

`diagm` constructs a full matrix; if you want storage-efficient versions with fast arithmetic, see [`Diagonal`](@ref), [`Bidiagonal`](@ref) [`Tridiagonal`](@ref) and [`SymTridiagonal`](@ref).

# Examples

```jldoctest
julia> diagm(1 => [1,2,3])
4×4 Matrix{Int64}:
 0  1  0  0
 0  0  2  0
 0  0  0  3
 0  0  0  0

julia> diagm(1 => [1,2,3], -1 => [4,5])
4×4 Matrix{Int64}:
 0  1  0  0
 4  0  2  0
 0  5  0  3
 0  0  0  0
```

---

```
diagm(v::AbstractVector)
diagm(m::Integer, n::Integer, v::AbstractVector)
```

Construct a matrix with elements of the vector as diagonal elements. By default, the matrix is square and its size is given by `length(v)`, but a non-square size `m`×`n` can be specified by passing `m,n` as the first arguments.

# Examples

```jldoctest
julia> diagm([1,2,3])
3×3 Matrix{Int64}:
 1  0  0
 0  2  0
 0  0  3
```


In [7]:
? triu

search: triu triu! istriu UpperTriangular LowerTriangular InteractiveUtils



```
triu(M)
```

Upper triangle of a matrix.

# Examples

```jldoctest
julia> a = fill(1.0, (4,4))
4×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

julia> triu(a)
4×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 0.0  1.0  1.0  1.0
 0.0  0.0  1.0  1.0
 0.0  0.0  0.0  1.0
```

---

```
triu(M, k::Integer)
```

Returns the upper triangle of `M` starting from the `k`th superdiagonal.

# Examples

```jldoctest
julia> a = fill(1.0, (4,4))
4×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

julia> triu(a,3)
4×4 Matrix{Float64}:
 0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

julia> triu(a,-3)
4×4 Matrix{Float64}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
```


In [11]:
diagm(0=>lambda)

100×100 Matrix{Int64}:
 11   0   0   0   0   0   0   0   0   0  …    0    0    0    0    0    0    0
  0  12   0   0   0   0   0   0   0   0       0    0    0    0    0    0    0
  0   0  13   0   0   0   0   0   0   0       0    0    0    0    0    0    0
  0   0   0  14   0   0   0   0   0   0       0    0    0    0    0    0    0
  0   0   0   0  15   0   0   0   0   0       0    0    0    0    0    0    0
  0   0   0   0   0  16   0   0   0   0  …    0    0    0    0    0    0    0
  0   0   0   0   0   0  17   0   0   0       0    0    0    0    0    0    0
  0   0   0   0   0   0   0  18   0   0       0    0    0    0    0    0    0
  0   0   0   0   0   0   0   0  19   0       0    0    0    0    0    0    0
  0   0   0   0   0   0   0   0   0  20       0    0    0    0    0    0    0
  0   0   0   0   0   0   0   0   0   0  …    0    0    0    0    0    0    0
  0   0   0   0   0   0   0   0   0   0       0    0    0    0    0    0    0
  0   0   0   0   0   0   0   0   0   0  

In [9]:
lambda = @. 10 + (1:100)
A = triu(rand(100,100),1) + diagm(0=>lambda)
b = rand(100)

100-element Vector{Float64}:
 0.10044745545696498
 0.792854072220451
 0.744498498084994
 0.3166283908189521
 0.6870675480759653
 0.013001181809404794
 0.4910139912092013
 0.2701392734603625
 0.019583902493276684
 0.7521758374746678
 0.09660113156945993
 0.29802257163068635
 0.4963735531629234
 ⋮
 0.37066175144151714
 0.3243696216223201
 0.3929099691524449
 0.7697105240601638
 0.41383125324976466
 0.19682510184561153
 0.16876292885266597
 0.2744691033905765
 0.34442127282034096
 0.4123015260938385
 0.18649235563624966
 0.08665156361785198

In [10]:
A

100×100 Matrix{Float64}:
 11.0   0.357869   0.262715   0.387345  …    0.80145      0.13673
  0.0  12.0        0.869573   0.351938       0.6078       0.320329
  0.0   0.0       13.0        0.201786       0.467997     0.699637
  0.0   0.0        0.0       14.0            0.312203     0.809498
  0.0   0.0        0.0        0.0            0.558395     0.921029
  0.0   0.0        0.0        0.0       …    0.651548     0.880385
  0.0   0.0        0.0        0.0            0.340944     0.729471
  0.0   0.0        0.0        0.0            0.961611     0.177251
  0.0   0.0        0.0        0.0            0.585125     0.923866
  0.0   0.0        0.0        0.0            0.604031     0.599294
  0.0   0.0        0.0        0.0       …    0.345449     0.35872
  0.0   0.0        0.0        0.0            0.501924     0.193023
  0.0   0.0        0.0        0.0            0.471946     0.293361
  ⋮                                     ⋱               
  0.0   0.0        0.0        0.0            0.96

In [37]:
m = 30
ki = zeros(100)
Km = zeros(100,30)
for i in 1:m
    k1 = 
    Km[:,i] = (A^i * b)
end

In [38]:
Km

100×30 Matrix{Float64}:
 21.7923   2036.4        1.87751e5  …  4.53269e55  4.83811e57  5.16927e59
 34.1158   2516.88       2.21641e5     4.82529e55  5.14183e57  5.48513e59
 31.4546   2310.81       2.03332e5     4.48603e55  4.78624e57  5.11194e59
 25.8531   2228.29       2.01596e5     4.47087e55  4.77035e57  5.0954e59
 30.9186   2300.32       2.03863e5     4.46108e55  4.75676e57  5.07768e59
 19.4005   1981.38       1.84137e5  …  4.35083e55  4.64814e57  4.97084e59
 30.3187   2466.12       2.20257e5     4.69764e55  5.00668e57  5.34197e59
 24.0759   2146.74       1.9675e5      4.48326e55  4.78369e57  5.1097e59
 22.4528   2333.55       2.17371e5     4.48081e55  4.77503e57  5.0945e59
 37.2795   2662.83       2.26784e5     4.84886e55  5.1741e57   5.52709e59
 24.9882   2494.96       2.31182e5  …  5.1983e55   5.54809e57  5.92764e59
 26.9685   2370.88  214407.0           4.59061e55  4.89187e57  5.21854e59
 32.2915   2579.73       2.2753e5      4.72717e55  5.03545e57  5.36982e59
  ⋮              

In [20]:
? range

search: range LinRange UnitRange StepRange StepRangeLen trailing_zer

```
range(start, stop, length)
range(start, stop; length, step)
range(start; length, stop, step)
range(;start, length, stop, step)
```

Construct a specialized array with evenly spaced elements and optimized storage (an [`AbstractRange`](@ref)) from the arguments. Mathematically a range is uniquely determined by any three of `start`, `step`, `stop` and `length`. Valid invocations of range are:

  * Call `range` with any three of `start`, `step`, `stop`, `length`.
  * Call `range` with two of `start`, `stop`, `length`. In this case `step` will be assumed

to be one. If both arguments are Integers, a [`UnitRange`](@ref) will be returned.

# Examples

```jldoctest
julia> range(1, length=100)
1:100

julia> range(1, stop=100)
1:100

julia> range(1, step=5, length=100)
1:5:496

julia> range(1, step=5, stop=100)
1:5:96

julia> range(1, 10, length=101)
1.0:0.09:10.0

julia> range(1, 100, step=5)
1:5:96

julia> range(stop=10, length=5)
6:10

julia> range(stop=10, step=1, length=5)
6:1:10

julia> range(start=1, step=1, stop=10)
1:1:10
```

If `length` is not specified and `stop - start` is not an integer multiple of `step`, a range that ends before `stop` will be produced.

```jldoctest
julia> range(1, 3.5, step=2)
1.0:2.0:3.0
```

Special care is taken to ensure intermediate values are computed rationally. To avoid this induced overhead, see the [`LinRange`](@ref) constructor.

!!! compat "Julia 1.1"
    `stop` as a positional argument requires at least Julia 1.1.


!!! compat "Julia 1.7"
    The versions without keyword arguments and `start` as a keyword argument require at least Julia 1.7.


---

```
range(start::T; stop::T, length=100) where T<:Colorant
range(start::T, stop::T; length=100) where T<:Colorant
```

Generates N (=`length`) >2 colors in a linearly interpolated ramp from `start` to`stop`, inclusive, returning an `Array` of colors.

!!! compat "Julia 1.1"
    `stop` as a positional argument requires at least Julia 1.1.



os



#### b)

In [3]:
function arnoldi(A,u,m)

# Application de la méthode d'Arnoldi sur la matrice A de dimensions m x n, qui
# forme un sous-espace de dimension m, en partant du vecteur initial u de
# dimension n.
# Retourne la base orthonormale de dimension m+1 et la matrice de Hessenberg
# supérieure H de dimensions (m+1) x m.

n = length(u)
Q = zeros(n,m+1)
H = zeros(m+1,m)
Q[:,1] = u/norm(u)
for j = 1:m
  v = A*Q[:,j]
  for i = 1:j
    H[i,j] = dot(Q[:,i],v)
    v -= H[i,j]*Q[:,i]
  end
  H[j+1,j] = norm(v)
  Q[:,j+1] = v/H[j+1,j]
end

return Q,H
end

arnoldi (generic function with 1 method)

In [ ]:
Q,H = arnoldi(A,u,m)

### Question 2

### Question 3